### ISSUE TITLE
Out of GPU Memory on RTX 3060 with 6GB VRAM When Processing a 10-Second Clip

### ISSUE THREAD

**Issue by snenyl** [prs-eth/RollingDepth#4]
I encountered an issue while running the pipeline on a 10-second video clip. The process fails due to a CUDA out-of-memory error, despite using an RTX 3060 with 6GB of VRAM. Additionally, the process seems to consume a significant amount of system RAM.

Here are the details:

**Command Used:**
`python3 run_video.py -i video/ -o output/samples_fast -p fast --save-npy true --verbose`

**Error Traceback:**

> Traceback (most recent call last):                                                                                                                            
  File "/home/nylund/Documents/Git/RollingDepth/run_video.py", line 490, in <module>
    pipe_out: RollingDepthOutput = pipe(
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/rollingdepth/rollingdepth_pipeline.py", line 135, in __call__
    pipe_output = self.forward(
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/rollingdepth/rollingdepth_pipeline.py", line 266, in forward
    rgb_latent = self.encode_rgb(
  File "/home/nylund/Documents/Git/RollingDepth/rollingdepth/rollingdepth_pipeline.py", line 690, in encode_rgb
    h = self.vae.encoder(batch)
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/diffusers/src/diffusers/models/autoencoders/vae.py", line 172, in forward
    sample = down_block(sample)
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/diffusers/src/diffusers/models/unets/unet_2d_blocks.py", line 1492, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/venv/rollingdepth/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nylund/Documents/Git/RollingDepth/diffusers/src/diffusers/models/resnet.py", line 371, in forward
    output_tensor = (input_tensor + hidden_states) / self.output_scale_factor
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 360.00 MiB. GPU 0 has a total capacity of 5.80 GiB of which 292.81 MiB is free. Including non-PyTorch memory, this process has 4.70 GiB memory in use. Of the allocated memory 4.51 GiB is allocated by PyTorch, and 70.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

If the model or pipeline requires more than 6GB of VRAM, could this limitation be highlighted in the documentation?

**Comment by markkua** [comment]
Hi, thanks for your interest. You can try to process at a smaller resolution. I have tested this setting on my 3090 and the peak memory consumption is lower than 6GB.
```bash
python run_video.py \
    -i data/samples \
    -o output/samples_fast \
    -p fast \
    --save-npy true \
    --verbose \
    --max-vae-bs 1 \
    --res 512
``` 
`--max-vae-bs 1` limits the batch size of the encoder and decoder, to save memory, 
with `--res 512`, the video will be downsampled such that the long side is at 512 pixels. 

btw, our method can process long videos with marginal memory increase.

**Comment by snenyl** [comment]
Thanks! That worked great!
